InventarioVeterinariaJoaquinBarrosVicenteFalcon/urls.py
from django.contrib import admin
from django.urls import path, include
from gestorUser.views import *
from gestorProductos.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('', home, name='home'),
    path('signup/', signup, name='signup'),
    path('home_panel/', home_panel, name='home_panel'),

    path('username_change/', username_change, name='username_change'),
    path('email_change/', email_change, name='email_change'),
    path('password_change/', password_change, name='password_change'),
    
    path('categories_list/', categories_list, name='categories_list'),
    path('categories_create/', categories_create, name='categories_create'),
    path('categories_edit/<int:id>/', categories_edit, name='categories_edit'),
    path('categories_delete/<int:id>/', categories_delete, name='categories_delete'),
    
    path('products_list/', products_list, name='products_list'),
    path('products_create/', products_create, name='products_create'),
    path('products_edit/<int:id>/', products_edit, name='products_edit'),
    path('products_delete/<int:id>/', products_delete, name='products_delete'),
]

gestorUser/forms.py
from django import forms
from django.contrib.auth.models import User

class UsuarioRegistroForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    first_name = forms.CharField(max_length=100, label="Nombre", required=True)
    last_name = forms.CharField(max_length=100, label="Apellido", required=True)
    email = forms.EmailField(label="Correo Electrónico", required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(), label="Contraseña", required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Confirmar Contraseña", required=True)
    
    first_name.widget.attrs['class'] = 'form-control'
    last_name.widget.attrs['class'] = 'form-control'
    email.widget.attrs['class'] = 'form-control'
    password1.widget.attrs['class'] = 'form-control'
    password2.widget.attrs['class'] = 'form-control'

    first_name.label= "Nombre"
    last_name.label= "Apellido"
    email.label= "Email"
    password1.label= "Contraseña"
    password2.label= "Confirmar Contraseña"

class UsuarioUsernameChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField(max_length=100, label="Nombre de usuario", required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña", required=True)
    
    username.widget.attrs['class'] = 'form-control'
    password.widget.attrs['class'] = 'form-control'

    username.label= "Nombre de usuario"
    password.label= "Contraseña"

class UsuarioEmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']

    email = forms.EmailField(label="Correo electrónico", required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña", required=True)
    
    email.widget.attrs['class'] = 'form-control'
    password.widget.attrs['class'] = 'form-control'

    email.label= "Correo electrónico"
    password.label= "Contraseña"

class UsuarioPasswordChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['password', 'new_password', 'new_password_confirmation']

    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña", required=True)
    new_password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña nueva", required=True)
    new_password_confirmation = forms.CharField(widget=forms.PasswordInput(), label="Confirmar contraseña nueva", required=True)
    
    password.widget.attrs['class'] = 'form-control'
    new_password.widget.attrs['class'] = 'form-control'
    new_password_confirmation.widget.attrs['class'] = 'form-control'

    password.label= "Contraseña"
    new_password.label= "Contraseña nueva"
    new_password_confirmation.label= "Confirmar contraseña nueva"

templates/user_views/user_settings/email_change.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Cambiar correo electrónico{% endblock %}
{% block sidebar %}

{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}

{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}
<!-- Form para añadir usuario-->
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold">
                    Cambiar correo electrónico
                </h1>
                <h3 class="text-center">Correo electrónico actual: {{ user.email }}</h3>
            </div>
        </div>
    </div>
</div>

{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{field.label}}: </strong> {{error}} </li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li> {{error}} </li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="row justify-content-center">
    <form method="post" class="user col-lg-8 card p-4">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control form-control-user" name="email" id="id_email" autofocus required
                placeholder="Correo electrónico nuevo">
        </div>
        <div class="form-group">
            <input type="password" class="form-control form-control-user" name="password" id="id_password" autofocus
                required placeholder="Contraseña">
        </div>
        <button type="submit" class="btn btn-primary btn-user btn-block font-weight-bold">
            Cambiar correo electrónico
        </button>
    </form>
</div>


<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}

templates/user_views/user_settings/password_change.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Cambiar contraseña{% endblock %}
{% block sidebar %}

{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}

{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}
<!-- Form para añadir usuario-->
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold">
                    Cambiar contraseña
                </h1>
            </div>
        </div>
    </div>
</div>

{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{field.label}}: </strong> {{error}} </li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li> {{error}} </li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="row justify-content-center">
    <form method="post" class="user col-lg-8 card p-4">
        {% csrf_token %}
        <div class="form-group">
            <input type="password" class="form-control form-control-user" name="password" id="id_password" autofocus
                required placeholder="Contraseña actual">
        </div>
        <div class="form-group">
            <input type="password" class="form-control form-control-user" name="new_password" id="id_new_password"
                autofocus required placeholder="Contraseña nueva">
        </div>
        <div class="form-group">
            <input type="password" class="form-control form-control-user" name="new_password_confirmation"
                id="id_new_password_confirmation" autofocus required placeholder="Confirmar contraseña nueva">
        </div>
        <button type="submit" class="btn btn-primary btn-user btn-block font-weight-bold">
            Cambiar contraseña
        </button>
    </form>
</div>


<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}

templates/user_views/user_settings/username_change.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Cambiar nombre de usuario{% endblock %}
{% block sidebar %}

{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}

{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}
<!-- Form para añadir usuario-->
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold">
                    Cambiar nombre de usuario
                </h1>
                <h3 class="text-center">Nombre de usuario actual: {{ user.username }}</h3>
            </div>
        </div>
    </div>
</div>

{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{field.label}}: </strong> {{error}} </li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li> {{error}} </li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="row justify-content-center">
    <form method="post" class="user col-lg-8 card p-4">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control form-control-user" name="username" id="id_username" autofocus
                required placeholder="Nombre de usuario nuevo">
        </div>
        <div class="form-group">
            <input type="password" class="form-control form-control-user" name="password" id="id_password" autofocus
                required placeholder="Contraseña">
        </div>
        <button type="submit" class="btn btn-primary btn-user btn-block font-weight-bold">
            Cambiar nombre de usuario
        </button>
    </form>
</div>


<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}