InventarioVeterinariaJoaquinBarrosVicenteFalcon/urls.py
from django.contrib import admin
from django.urls import path, include
from gestorUser.views import *
from gestorProductos.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('', home, name='home'),
    path('signup/', signup, name='signup'),
    path('home_panel/', home_panel, name='home_panel'),

    path('username_change/', username_change, name='username_change'),
    path('email_change/', email_change, name='email_change'),
    path('password_change/', password_change, name='password_change'),
    
    path('categories_list/', categories_list, name='categories_list'),
    path('categories_create/', categories_create, name='categories_create'),
    path('categories_edit/<int:id>/', categories_edit, name='categories_edit'),
    path('categories_delete/<int:id>/', categories_delete, name='categories_delete'),
    
    path('products_list/', products_list, name='products_list'),
    path('products_create/', products_create, name='products_create'),
    path('products_edit/<int:id>/', products_edit, name='products_edit'),
    path('products_delete/<int:id>/', products_delete, name='products_delete'),
]

gestorProductos/forms.py
from django import forms

from .models import Categoria, Producto

class CategoriaRegistroForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['name', 'description']

    name = forms.CharField(max_length=100, label="Nombre", required=True)
    description = forms.CharField(max_length=100, label="Descripción", required=True)
    
    name.widget.attrs['class'] = 'form-control'
    description.widget.attrs['class'] = 'form-control'

    name.label= "Nombre"
    description.label= "Descripción"

class CategoriaEditarForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['name', 'description']

    name = forms.CharField(max_length=100, label="Nombre", required=True)
    description = forms.CharField(max_length=100, label="Descripción", required=True)
    
    name.widget.attrs['class'] = 'form-control'
    description.widget.attrs['class'] = 'form-control'

    name.label= "Nombre"
    description.label= "Descripción"

class ProductoRegistroForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['name', 'description', 'price', 'category']

    name = forms.CharField(max_length=100, label="Nombre", required=True)
    description = forms.CharField(max_length=100, label="Descripción", required=True)
    price = forms.IntegerField(min_value=0, label="Precio", required=True)
    category = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        label="Categoría",
        required=True,
        widget=forms.Select(attrs={'class': 'form-control form-control-user'}),
        empty_label="Seleccione una categoría"
    )
    
    name.label= "Nombre"
    description.label= "Descripción"
    price.label= "Precio"
    category.label= "Categoría"

class ProductoEditarForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['name', 'description', 'price', 'category']
    
    name = forms.CharField(max_length=100, label="Nombre", required=True)
    description = forms.CharField(max_length=100, label="Descripción", required=True)
    price = forms.IntegerField(min_value=0, label="Precio", required=True)
    category = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        label="Categoría",
        required=True,
        widget=forms.Select(attrs={'class': 'form-control form-control-user'}),
        empty_label="Seleccione una categoría"
    )

    name.label= "Nombre"
    description.label= "Descripción"
    price.label= "Precio"
    category.label= "Categoría"

templates/user_views/products_control/products_create.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Registrar producto{% endblock %}
{% block sidebar %}

{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}

{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}
<!-- Form para registrar producto-->
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold mb-4">
                    Registrar producto
                </h1>
                <hr>
            </div>
            <form method="post" class="user">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" name="name" id="id_name" autofocus
                        required placeholder="Nombre">
                </div>
                <div class="form-group">
                    <textarea class="form-control form-control-user" name="description" id="id_description" autofocus
                        required placeholder="Descripción"></textarea>
                </div>
                <div class="form-group">
                    <input type="number" class="form-control form-control-user" name="price" id="id_price" autofocus
                        required placeholder="Precio">
                </div>
                <div class="form-group">
                    {{ form.category }}
                </div>
                <button class="btn btn-primary btn-user btn-block font-weight-bold" type="submit">
                    Registrar producto
                </button>
            </form>
        </div>
    </div>
</div>


{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{field.label}}: </strong> {{error}} </li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li> {{error}} </li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}

templates/user_views/products_control/products_edit.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Editar producto{% endblock %}
{% block sidebar %}
{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}
{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}
<!-- Form para editar producto-->
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold">
                    Editar producto
                </h1>
            </div>
        </div>
    </div>
</div>

{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{field.label}}: </strong> {{error}} </li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li> {{error}} </li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="row justify-content-center my-5">
    <form method="post" class="user col-lg-8 card p-4">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control form-control-user" name="name" id="id_name" autofocus required
                placeholder="Nombre" value="{{ prod.nombre }}">
        </div>
        <div class="form-group">
            <textarea class="form-control form-control-user" name="description" id="id_description" autofocus required
                placeholder="Descripción">{{ prod.descripcion }}</textarea>
        </div>
        <div class="form-group">
            <input type="number" class="form-control form-control-user" name="price" id="id_price" autofocus required
                placeholder="Precio" value="{{ prod.precio }}">
        </div>
        <div class="form-group">
            {{ form.category }}
        </div>
        <button class="btn btn-primary btn-user btn-block font-weight-bold" type="submit">
            Editar producto
        </button>
        <a href="{% url 'products_list' %}" class="btn btn-secondary btn-user btn-block font-weight-bold">
            Volver al listado de productos</a>
    </form>
</div>


<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}

templates/user_views/products_control/products_list.html
{% extends "base_general.html" %}
{% load static %}

{% block titulo %}Listado de productos{% endblock %}
{% block sidebar %}

{% if user.is_superuser %}
{% include 'user_views/super_user/sidebar.html' %}
{% else %}
{% include 'user_views/regular_user/sidebar.html' %}
{% endif %}

{% endblock %}
{% block topbar %} {% include 'menu/topbar_user_name.html' %} {% endblock %}
{% block content %}

<link rel="stylesheet" href="https://cdn.datatables.net/2.3.4/css/dataTables.dataTables.css" />

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="p-5">
            <div class="text-center">
                <h1 class="text-primary font-weight-bold">
                    Listado de productos
                </h1>
            </div>
        </div>
    </div>
</div>
<table id="productsTable" class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>Categoría</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if productos %} {% for prod in productos %} {% if user.is_superuser or prod.creador == user %}

        <tr>
            <td>{{prod.nombre}}</td>
            <td>{{prod.descripcion}}</td>
            <td>{{prod.precio}}</td>
            <td>{{prod.categoria}}</td>
            <td>
                <!-- Editar -->
                <a href="{% url 'products_edit' prod.id %}" class="btn btn-sm btn-secondary">
                    <i class="bi bi-pencil"></i>
                </a>

                {% if user.is_superuser %}
                <!-- Eliminar (desactivar)-->
                <button class="btn btn-sm btn-secondary" data-bs-toggle="modal"
                    data-bs-target="#modalDelete{{ prod.id }}">
                    <i class="bi bi-trash"></i>
                </button>
                {% endif %}
            </td>
        </tr>

        <!-- Modal para confirmar eliminación del producto -->
        <div class="modal fade" id="modalDelete{{ prod.id }}" tabindex="-1" aria-labelledby="modalLabel{{ prod.id }}"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel{{ prod.id }}">Confirmar eliminación</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>

                    <div class="modal-body">
                        ¿Estás seguro que deseas eliminar el producto <strong>{{ prod.nombre }}</strong>?
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button>
                        <a href="{% url 'products_delete' prod.id %}" class="btn btn-danger">Eliminar</a>
                    </div>

                </div>
            </div>
        </div>
        {% endif %}{% endfor %}{% endif %}
    </tbody>
</table>

<style>
    .btn-primary {
        background-color: var(--primary);
        color: white;
        border-color: white;
    }

    .btn-primary:hover {
        color: var(--primary);
        background-color: white;
        border-color: var(--primary);
    }

    .btn-primary:active:focus {
        background-color: var(--primary) !important;
        color: white !important;
        border-color: white !important;
    }

    .a {
        color: var(--primary);
    }

    .a:hover {
        color: var(--primary) !important;
    }
</style>
{% endblock %}
{% block scriptsTablas %}
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.3.4/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.3.4/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/dataTables.buttons.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/buttons.bootstrap5.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/3.2.5/js/buttons.colVis.min.js"></script>

<script>
    new DataTable("#productsTable", {
        layout: {
            topStart: {
                buttons: ["excel", "pdf"],
            },
            topEnd: 'search',
            bottomStart: null,
            bottomEnd: null
        },
        language: {
            url: "https://cdn.datatables.net/plug-ins/2.3.4/i18n/es-ES.json",
        },
    });
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
    crossorigin="anonymous"></script>
{% endblock %}
{% block footer %} {% include 'menu/footer.html' %} {% endblock %}
{% block extras %} {% include 'menu/logout_dialog.html' %} {% endblock %}